chat/urls.py
from django.urls import path
from .views import ChatListView, ChatCreateView, ChatDetailView, MessageDeleteView

urlpatterns = [

    path('chat-list', ChatListView.as_view(), name='chat_list'),
    path('chat/create/<slug:slug>', ChatCreateView.as_view(), name='chat_create'),
    path('chat-detail/<int:pk>', ChatDetailView.as_view(), name='chat_detail'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),





]

mango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import handler403, handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),

    path('', include('core.urls')),
    path('feedback/', include('feedback.urls')),
    path('users/', include('users.urls')),
    path('chat/', include('chat.urls')),

]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = handler403
handler404 = handler404
handler500 = handler500

users/urls.py
from django.urls import path, reverse_lazy
from .views import (SignUPView, UserLoginView, EmailConfirmationSentView, UserConfirmEmailView, EmailConfirmedView, \
                    EmailConfirmationFailedView, ProfileDetailView, UpdateProfileView, UserPasswordChangeView)
from django.contrib.auth.views import (LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
                                       PasswordResetCompleteView)

app_name = 'users'

urlpatterns = [
    # Авторизация Регитсрация Выход
    path('signup', SignUPView.as_view(), name='signup'),
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),

    # Верификация пользователя
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),

    # Профиль пользователя
    path('profile/<slug:slug>', ProfileDetailView.as_view(), name='profile'),
    path('profile/<slug:slug>/update', UpdateProfileView.as_view(), name='profile_update'),

    # Смена пароля
    path('password-change', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                     email_template_name='users/password_reset_email.html',
                                                     success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset-done', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]

templates/base.html
{% load static %}
{% load count_notification %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>{% block title %}{{ title }}{% endblock title %}</title>
    <link rel="shortcut icon" href="{% static 'core/img/mango.png' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    {% block style %}{% endblock style %}
</head>

<body>

<nav class="navbar navbar-light bg-light py-4 ">
    <div class="container">


        <div class="mx-auto">
            <a href="{% url 'home' %}"><i class="fa-solid fa-house   fa-2xl" style="color: #FFA500;"></i></a>
        </div>
        <div>

            <img src="{% static 'core/img/mango.png' %}" width="60"
                 height="50"><i
                class="fa-solid fa-m fa-beat-fade fa-sm">ango</i>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <div class="row">


        <div class="col-md-3 min-vh-100 overflow-auto border-end border-top border-2  shadow-lg rounded-3 bg-white" >
            <div class="position-fixed mx-4">
                {% if request.user.is_authenticated %}


                    <form action="{% url 'search_result' %}" method="get" class="text-center m-3">
                        <input type="text" name="person" placeholder="Поиск пользователя"
                               class="rounded-3 text-center p-2 rounded-pill border-2 border-dark">
                        <button class="border-0 bg-transparent" type="submit"><i
                                class="fa-solid fa-magnifying-glass fa-2xl text-warning"></i></button>
                    </form>


                    <div class="text-center mt-2">
                        <img class=" rounded-circle" src="{{ request.user.profile.picture.url }}" width="320px"
                             height="320px">
                    </div>

                    <div class=" mt-3 ">
                        <ul class=" fs-5 " style="list-style:none;">

                            <a class="text-decoration-none" href="{% url 'users:profile' request.user.profile.slug %}">
                                <li><i class='bx bxs-user bx-sm text-success'> Профиль</i></li>
                            </a>
                            <a class="text-decoration-none" href="{% url 'add_image' %}">
                                <li><i class='bx bxs-camera-plus bx-sm text-warning'> Добавить фото</i></li>
                            </a>
                            {% get_count as count_not %}
                            {% if count_not == 0 %}
                                <a class="text-decoration-none align-items-center"
                                   href="{% url 'notifications_list' %}">
                                    <li><i class='bx bxs-bell bx-sm text-danger'> Уведомления</i></li>
                                </a>
                            {% else %}
                                <a class="text-decoration-none align-items-center"
                                   href="{% url 'notifications_list' %}">
                                    <li><i class='bx bxs-bell bx-sm text-danger'> Уведомления <i
                                            class="fa-solid fa-circle fa-2xs text-danger"></i></i></li>
                                </a>
                            {% endif %}
                            <a class="text-decoration-none" href="{% url 'chat_list' %}">
                                <li><i class='bx bxs-envelope bx-sm text-info'> Сообщения</i></li>
                            </a>
                            <a class="text-decoration-none" href="{% url 'list_followers' request.user.profile.slug %}">
                                <li><i class='bx bxs-group bx-sm text-primary'> Мои подписчики</i></li>
                            </a>
                            <a class="text-decoration-none"
                               href="{% url 'list_subscriptions' request.user.profile.slug %}">
                                <i class="fa-solid fa-person-circle-check fa-lg text-success"> Подписки</i></li>
                            </a>
                        </ul>
                        <div class="d-grid gap-2 text-center my-3">
                            <a class="text-decoration-none btn btn-danger" href="{% url 'users:logout' %}"><i
                                    class='bx bx-log-out'> Выход</i></a>
                        </div>
                    </div>
                {% else %}
                    <div class="text-center mt-2">
                        <img class=" rounded-circle my-5" src="{% static 'core/img/default.png' %}" width="320"
                             height="320">
                    </div>
                    <div class="text-center mt-5 ">

                        <div class="d-grid gap-2 my-1">
                            <a class="text-decoration-none btn btn-warning text-primary rounded-pill p-3 border-2 border-light"
                               href="{% url 'users:login' %}">Войти</a>
                
                        </div>
                        <div class="d-grid gap-2">
                            <a class="text-decoration-none btn btn-primary rounded-pill p-3 border-2 border-light"
                               href="{% url 'users:signup' %}">
                                Регистрация</a>
                        </div>

                    </div>
                {% endif %}

            </div>
        </div>


        <div class="col-md-9  bg-light">
            {% if messages %}

                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        <strong>{{ message }}</strong>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрыть"></button>
                    </div>
                {% endfor %}

            {% endif %}

            {% block main %}
            {% endblock main %}


        </div>
    </div>
</div>

</body>

</html>