chat/urls.py
from django.urls import path
from .views import ChatListView, ChatCreateView, ChatDetailView, MessageDeleteView

urlpatterns = [

    path('chat-list', ChatListView.as_view(), name='chat_list'),
    path('chat/create/<slug:slug>', ChatCreateView.as_view(), name='chat_create'),
    path('chat-detail/<int:pk>', ChatDetailView.as_view(), name='chat_detail'),
    path('message/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),





]

mango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import handler403, handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('captcha/', include('captcha.urls')),

    path('', include('core.urls')),
    path('feedback/', include('feedback.urls')),
    path('users/', include('users.urls')),
    path('chat/', include('chat.urls')),

]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler403 = handler403
handler404 = handler404
handler500 = handler500

users/urls.py
from django.urls import path, reverse_lazy
from .views import (SignUPView, UserLoginView, EmailConfirmationSentView, UserConfirmEmailView, EmailConfirmedView, \
                    EmailConfirmationFailedView, ProfileDetailView, UpdateProfileView, UserPasswordChangeView)
from django.contrib.auth.views import (LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
                                       PasswordResetCompleteView)

app_name = 'users'

urlpatterns = [
    # Авторизация Регитсрация Выход
    path('signup', SignUPView.as_view(), name='signup'),
    path('login', UserLoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),

    # Верификация пользователя
    path('email-confirmation-sent/', EmailConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm-email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email-confirmed/', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('confirm-email-failed/', EmailConfirmationFailedView.as_view(), name='email_confirmation_failed'),

    # Профиль пользователя
    path('profile/<slug:slug>', ProfileDetailView.as_view(), name='profile'),
    path('profile/<slug:slug>/update', UpdateProfileView.as_view(), name='profile_update'),

    # Смена пароля
    path('password-change', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                     email_template_name='users/password_reset_email.html',
                                                     success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset-done', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy('users:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),

]

users/models.py
from django.conf import settings
from django.core.mail import send_mail
from django.urls import reverse
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.utils.timezone import now
from django_countries.fields import CountryField
from datetime import datetime

GENDER = [('Woman', 'Женский'), ('Man', 'Мужской'), ('Not_defined', 'Не указан')]


class Profile(models.Model):
    '''Модель Профиль'''

    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='пользователь')
    first_name = models.CharField('имя', max_length=50, blank=True, null=True)
    last_name = models.CharField('фамилия', max_length=50, blank=True, null=True)
    bio = models.TextField('о себе', max_length=500, blank=True, null=True)
    birth_date = models.DateField('дата рождения', null=True, blank=True, default=timezone.now)
    country = CountryField(null=True, blank=True)
    private = models.BooleanField('приватность', default=False)
    gender = models.CharField(choices=GENDER, default='Not_defined', blank=True, null=True, verbose_name='пол', max_length=16)
    online = models.BooleanField(default=False, verbose_name='статус')
    picture = models.ImageField(upload_to='uploads/profile_pictures', default='default/default.png',
                                blank=True)
    followers = models.ManyToManyField(User, blank=True, related_name='followers')
    slug = models.SlugField('слаг', blank=True, null=True)

    @property
    def age(self):
        now_date = datetime.now().year
        return now_date - self.birth_date.year

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = self.user.username.lower().replace(' ', '-')
            self.slug = slug
            # self.slug = slugify(self, self.user.username)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Профиль пользователя {self.slug}'

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def get_absolute_url(self):
        return reverse('users:profile', kwargs={'slug': self.user.username})



users/forms.py
from datetime import datetime
from django.contrib.auth import get_user_model
from django.forms import ValidationError
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

from users.models import Profile


class SignUPForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError(
                'Пользователь с таким email уже существует!')
        return email


class ProfileForm(forms.ModelForm):
    bio = forms.CharField(label='О себе', required=False, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Введите о себе информацию'}))
    country = CountryField()
    now_year = datetime.now().year
    birth_date = forms.DateField(label='Дата рождения',
                                 widget=forms.SelectDateWidget(years=tuple(range(now_year - 80, now_year - 5))))

    class Meta:
        model = Profile
        exclude = ('followers', 'user', 'slug', 'subscriptions', 'online')
        widgets = {"country": CountrySelectWidget(),
                   'birth_date': forms.SelectDateWidget(
                       attrs={'class': 'form-control'})
                   }
        labels = {
            'picture': 'Аватарка',
            'country': ' Страна'
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='Старый пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(
        label='Новый пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label='Подтверждение пароля',
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError(
                'Пользователь с таким email уже существует!')
        return email

users/views.py
from django.conf.global_settings import EMAIL_HOST_USER
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import PasswordChangeView
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import CreateView, DetailView, UpdateView, TemplateView
from django.contrib.auth.forms import AuthenticationForm
from core.models import ProfileImage
from common.utils import TitleMixin
from .tasks import send_email_verification_task
from .forms import SignUPForm, ProfileForm, UserPasswordChangeForm
from .models import Profile
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.sites.models import Site


User = get_user_model()


class SignUPView(TitleMixin, SuccessMessageMixin, CreateView):
    '''Регистрация'''

    model = User
    form_class = SignUPForm
    template_name = 'users/signup.html'
    success_message = 'Пользователь успешно зарегистрирован'
    title = 'Регистрация'

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        # Функционал для генерации токена
        token = default_token_generator.make_token(user)
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        activation_url = reverse_lazy('users:confirm_email', kwargs={
                                      'uidb64': uid, 'token': token})
        current_site = Site.objects.get_current().domain

        send_email_verification_task.delay(
            user.email, current_site,  activation_url)

        return redirect('users:email_confirmation_sent')


class UserLoginView(TitleMixin, SuccessMessageMixin, LoginView):
    '''Авторизация'''

    template_name = 'users/login.html'
    form_class = AuthenticationForm
    success_message = 'Вы вошли на сайт'
    title = 'Авторизация'
    success_url = reverse_lazy('home')


class ProfileDetailView(TitleMixin, LoginRequiredMixin, DetailView):
    '''Вывод профиля'''

    model = Profile
    template_name = 'users/profile.html'
    context_object_name = 'profile'
    title = 'Профиль'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        images = ProfileImage.objects.filter(profile=self.object)
        context['count_likes'] = sum(photo.likes.count() for photo in images)
        return context


class UpdateProfileView(TitleMixin, LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    '''Редактировать личные данные'''

    model = Profile
    form_class = ProfileForm
    template_name = 'users/update-profile.html'
    title = 'Редактирование профиля'
    success_message = 'Вы успешно обновили данные!'

    def get_success_url(self):
        print(self.kwargs)
        return reverse('users:profile', kwargs={'slug': self.object.slug})


class UserPasswordChangeView(TitleMixin, LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    '''Сменить пароль'''

    form_class = UserPasswordChangeForm
    template_name = 'users/password_change.html'
    success_url = reverse_lazy('home')
    success_message = 'Вы успешно изменили пароль!'
    title = 'Смена пароля'


class UserConfirmEmailView(View):
    def get(self, request, uidb64, token):
        try:
            uid = urlsafe_base64_decode(uidb64)
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            return redirect('users:email_confirmed')
        else:
            return redirect('users:email_confirmation_failed')


class EmailConfirmationSentView(TitleMixin, TemplateView):
    template_name = 'users/verification/email_confirmation_sent.html'
    title = "Письмо активации отправлено"


class EmailConfirmedView(TitleMixin, TemplateView):
    template_name = 'users/verification/email_confirmed.html'
    title = "Ваш электронный адрес активирован"


class EmailConfirmationFailedView(TitleMixin, TemplateView):
    template_name = 'users/verification/email_confirmation_failed.html'
    title = "Ваш электронный адрес не активирован"

templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    {% block style %}{% endblock style %}
</head>
<body class="signupClass ">
{% if messages %}

    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            <strong>{{ message }}!</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Закрыть"></button>
        </div>
    {% endfor %}

{% endif %}
{% block main %}
{% endblock main %}
</body>
</html>

templates/users/login.html
{% extends 'users/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block style %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
{% endblock style %}
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
{% block title %}
    Авторизация
{% endblock title %}
{% block main %}



    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-dark text-white" style="border-radius: 1rem;">
                        <div class="card-body p-3 text-center">

                            <div class="mb-md-5 pb-5">

                                <h2 class="fw-bold mb-2 text-uppercase text-warning">Авторизация</h2>
                                <p class="text-white-50 mb-5">Пожалуйста введите свой логин и пароль</p>
                                <img src="{% static 'core/img/mango.png' %}" width="100px" height="auto">

                                <form action="" method="post" class="">
                                    {% csrf_token %}
                                    <div class="card-body">
                                        {{ form|crispy }}
                                    </div>
                                    <div class="px-3">
                                        <div class="d-grid gap-2">
                                            <button class="btn btn-outline-warning" type="submit">Войти</button>
                                        </div>

                                    </div>

                                </form>

                                <div class="d-flex justify-content-center text-center mt-4 pt-1">
                                    <a href="{% url 'social:begin' 'github' %}" class="text-white me-3"><i
                                            class="fa-brands fa-github fa-2xl"></i></a>
                                    <a href="{% url 'social:begin' 'vk-oauth2' %}" class="text-white"><i
                                            class="fa-brands fa-vk fa-2xl"></i></a>

                                </div>

                            </div>

                            <div class="d-flex flex-row justify-content-evenly">
                                <p class="mb-0">Нет аккаунта?
                                    <a href="{% url 'users:signup' %}"
                                       class="text-warning text-decoration-none fw-bold">Создать</a>
                                </p>


                                <a href="{% url 'users:password_reset' %}"
                                   class="text-warning text-decoration-none fw-bold">Забыли пароль</a>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock main %}

templates/users/password_change.html
{% extends 'users/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block style %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}">
{% endblock style %}
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
{% block title %}
    Авторизация
{% endblock title %}
{% block main %}



    <section class="vh-100 gradient-custom">
        <div class="container py-2 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card bg-dark text-white" style="border-radius: 1rem;">
                        <div class="card-body p-3 text-center">

                            <div class="mb-md-5 pb-2">

                                <h2 class="fw-bold mb-2 text-uppercase text-warning">Смена пароля</h2>
                                <img src="{% static 'core/img/mango.png' %}" width="80px" height="auto">

                                <form action="" method="post" class="">
                                    {% csrf_token %}
                                    <div class="card-body">
                                        {{ form|crispy }}
                                    </div>
                                    <div class="">
                                        <div class="d-grid gap-2">
                                            <button class="btn btn-outline-warning mx-3" type="submit">Обновить пароль
                                            </button>
                                        </div>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock main %}

templates/users/password_reset_complete.html
{% extends "users/base.html" %}
{% load i18n %}

{% block main %}

    <p>Поздравляем, вы успешно изменили пароль своего аккаунта. Используйте его для
        <a href="{%  url 'users:login' %}">входа в систему</a></p>



{% endblock main %}

templates/users/password_reset_confirm.html
{% extends "users/base.html" %}
{% load i18n static %}
{% block title %}Новый пароль{% endblock title %}
{% load crispy_forms_tags %}

{% block main %}

    <h1>Новый пароль/h1>

        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <button type="submit">Сохранить</button>
        </form>

{% endblock main %}

templates/users/password_reset_done.html
{% extends "users/base.html" %}
{% load i18n %}

<h1>Сброс пароля</h1>

{% block main %}

    <p>Мы отправили вам по электронной почте инструкции по установке пароля,
        если существует учетная запись с указанным вами адресом электронной почты.
        Вы должны получить их в ближайшее время</p>

    <p>Если вы не получили электронное письмо, убедитесь, что вы ввели адрес,
        под которым зарегистрировались, и проверьте папку со спамом.</p>

{% endblock main %}

templates/users/profile.html
{% extends 'base.html' %}

{% load static %}

{% load count_notification %}


{% block main %}



    {% get_count as count %}

    <div class="container">

        <div class="row d-flex justify-content-center">

            <div class="col-md-8">

                <div class="card py-3 shadow-lg">
                    {% if profile.user != request.user %}
                        {% if profile.online %}
                            <div class="online-status text-center mb-4 ">

                                <span class=" p-2 bg-primary text-white rounded-2 rounded-pill">В сети</span>
                            </div>
                        {% else %}
                            <div class="offline-status text-danger text-center mb-4">
                                <span class=" p-2 bg-danger text-white rounded-2 rounded-pill">Не в сети</span>

                            </div>
                        {% endif %}
                    {% else %}
                        <div class="online-status text-center mb-4 ">

                            <span class=" p-2 bg-primary text-white rounded-2 rounded-pill">Это Вы</span>
                        </div>
                    {% endif %}
                    <div class="text-center">
                        <img src="{{ profile.picture.url }}" width="200" height="200" class="rounded-circle shadow-sm">
                    </div>

                    <div class="text-center mt-3">
                        <span class=" rounded text-white"><img src="{{ profile.country.flag }}"
                                                               title="{{ profile.country.name }}" width="35px"
                                                               height="25px"></span>
                        <h5 class="mt-2 mb-0">{{ profile.first_name }} {{ profile.last_name }}</h5>
                        <span>Пол: {{ profile.get_gender_display }}</span><br>
                        <span>{{ profile.age }} лет</span>

                        <div class="px-4 mt-1">
                            {% if profile.bio %}
                                <p class="fonts">{{ profile.bio }}. </p>
                            {% endif %}
                        </div>
                    </div>
                    <table class="table text-center">
                        <thead>
                        <tr>
                            <th scope="col">Подписчики</th>
                            <th scope="col">Фотографии</th>
                            <th scope="col">Лайки</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><a class="text-decoration-none"
                                   href="{% url 'list_followers'  profile.slug %}">{{ profile.followers.all.count }}</a>
                            </td>
                            <td>{{ profile.profile_images.all.count }}</td>
                            <td>{{ count_likes }}</td>
                        </tr>
                        <tr>
                    </table>


                    <div class="d-flex flex-row justify-content-center">


                        {% if request.user == profile.user %}
                            <a class="btn btn-success rounded-pill"
                               href="{% url 'users:profile_update' profile.slug %}">Редактировать
                                профиль</a>
                        {% else %}
                            {% if request.user in profile.followers.all %}
                                <form action="{% url 'remove_follower' profile.slug %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger rounded-pill mx-3">Отписаться
                                    </button>
                                </form>
                                <form method="POST" action="{% url 'chat_create' profile.slug %}">
                                    {% csrf_token %}
                                    <button class="btn btn-primary rounded-pill " type="submit">
                                        Написать

                                    </button>
                                </form>
                            {% else %}
                                <form action="{% url 'add_follower' profile.slug %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-success rounded-pill mx-3">
                                        Подписаться
                                    </button>
                                </form>
                                <form method="POST" action="{% url 'chat_create' profile.slug %}">
                                    {% csrf_token %}
                                    <button class="btn btn-primary rounded-pill" type="submit">
                                        Написать

                                    </button>
                                </form>
                            {% endif %}

                        {% endif %}


                    </div>


                </div>

            </div>

        </div>

    </div>



    <div class="container-fluid border-top mt-3">

        <div class="row ">
            <div class="row align-items-md-stretch mb-5 bg-light">
                {% if profile.private and profile.user != request.user %}
                    <div class="alert alert-danger my-4">
                        <h6 class="text-center"><i class="fa-solid fa-lock fa-xl"></i>
                            Пользователь {{ profile.first_name }} {{ profile.last_name }}
                            ограничил доступ к своим фотографиям</h6>
                    </div>
                {% else %}
                    {% for image in profile.profile_images.all %}
                        <div class="col-md-4">
                            <a href="{{ image.get_absolute_url }}">
                                <img height="260px" width="260px" src="{{ image.photo.url }}"
                                     class="card-img-top rounded-3 my-3 mx-1 shadow-lg">
                            </a>

                        </div>
                    {% empty %}
                        <div class="alert alert-danger my-5">
                            <h3 class="text-center">Фотографий нет</h3>
                        </div>

                    {% endfor %}

                {% endif %}
            </div>
        </div>
    </div>

{% endblock main %}

templates/users/signup.html
{% extends 'users/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block style %}
{% endblock style %}

{% block title %}
    Регистрация
{% endblock title %}
{% block main %}


    <section class="min-vh-100" style="background-color: #eee;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-75">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body ">
                            <div class="row justify-content-center">

                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                    <div class="card bg-dark py-1 px-3 ">
                                        <h4 class="text-center text-warning  fw-bold mb-2 mx-1 mx-md-4 mt-2">
                                            Регистрация</h4>

                                        <form action="" method="post" class="text-warning">
                                            {% csrf_token %}
                                            {{ form|crispy }}
                                            <div class="d-grid gap-2">
                                                <button class="btn btn-outline-warning" type="submit">Создать аккаунт
                                                </button>
                                            </div>
                                        </form>

                                        <div class="text-center py-3 ">
                                            <a class="text-white fw-bold text-decoration-none" href="{% url 'users:login' %}">
                                                Есть аккаунт? <span class="text-warning">Войти</span></a>
                                        </div>
                                    </div>

                                </div>

                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                                    <img src="{% static 'users/img/index.png' %}"
                                         class="img-fluid" alt="Sample image">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock main %}

templates/users/update-profile.html
{% extends 'base.html' %}

{% block title %}
    Редактирование
{% endblock title %}

{% load static %}

{% load crispy_forms_tags %}

{% block style %}
    {#    <link rel="stylesheet" href="{% static 'core/css/update-profile.css' %}">#}
{% endblock style %}




{% block main %}
    <div class="container my-2">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <div class="card bg-dark text-white shadow-sm" style="border-radius: 1rem;">
                    <div class="card-body p-2 text-center">

                        <div class="my-2">

                            <h4 class="fw-bold mb-2 text-uppercase text-warning">Редактировать профиль</h4>
                            <img src="{% static 'core/img/mango.png' %}" width="80px" height="auto">

                            <form action="" method="post" enctype="multipart/form-data" class="">
                                {% csrf_token %}
                                <div class="card-body">
                                    {{ form|crispy }}
                                </div>
                                <div class="">
                                    <div class="d-grid gap-2 px-3">
                                        <button class="btn btn-outline-warning" type="submit">Обновить данные
                                        </button>
                                    </div>
                                      <div class="d-grid gap-2 px-3 pt-5">
                                          <a class="text-decoration-none text-danger " href="{% url 'users:password_change' %}">Сменить пароль</a>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock main %}

